In [3]:
import numpy as np

In [4]:
myarr=np.array([[3,6,32,7]],np.int64)

In [5]:
myarr

array([[ 3,  6, 32,  7]], dtype=int64)

In [6]:
myarr[0,1]

6

In [7]:
myarr.shape

(1, 4)

In [8]:
myarr.dtype

dtype('int64')

<!-- Array creation: conversion from other python structures -->

**Array creation: conversion from other python structures

In [9]:
listarr=np.array([[1,2,3],[5,8,5],[0,3,1]])

In [10]:
listarr

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [11]:
listarr.dtype

dtype('int32')

In [12]:
listarr.shape

(3, 3)

In [13]:
listarr.size

9

In [14]:
np.array({34,23})

array({34, 23}, dtype=object)

In [17]:
zeros=np.zeros((2,5))

In [18]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
zeros.dtype

dtype('float64')

In [20]:
rng=np.arange(15)

In [21]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
lspace=np.linspace(1,5,3)

In [27]:
lspace

array([1., 3., 5.])

In [29]:
emp=np.empty_like(lspace)

In [30]:
emp

array([1., 3., 5.])

In [31]:
ide=np.identity(45)

In [32]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [33]:
ide.shape

(45, 45)

In [34]:
arr=np.arange(99)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [37]:
arr=arr.reshape(3,33)

In [38]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [39]:
arr.ravel

<function ndarray.ravel>

In [40]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [43]:
arr=arr.ravel()

In [44]:
arr.shape

(99,)

In [45]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [46]:
ar=np.array(x)

In [47]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [48]:
ar.sum(axis=0)

array([12,  8,  9])

In [49]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [50]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [51]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [52]:
ar.flat

In [53]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [57]:
ar.ndim

2

In [58]:
ar.size

9

In [59]:
ar.nbytes

36

In [63]:
one=np.array([1,3,4,634,2])

In [65]:
one.argmax()

3

In [64]:
one.argmin()

0

In [66]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [67]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [68]:
ar.argmin()

8

In [69]:
ar.argmax()

6

In [70]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [71]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [72]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [73]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [74]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [75]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [76]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [77]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [78]:
arrr=np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [79]:
ar+arrr

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [80]:
ar*arrr

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [81]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [82]:
ar.sum()

29

In [83]:
ar.max()

7

In [84]:
ar.min()

0

In [85]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [86]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [87]:
np.count_nonzero(ar)

8

In [88]:
ar[1,2]=0

In [89]:
import sys

In [91]:
py_ar=[0,4,55,2]

In [92]:
np_ar=np.array(py_ar)

In [93]:
sys.getsizeof(1)*len(py_ar)

112

In [95]:
np_ar.itemsize*np_ar.size

16